# Compiles a plug-in's factory presets into it: every .txt under PRESET_DIR (its presets folder,
# sub-folders as categories) becomes a string in OUT, a C++ file that registers them with
# pk::presets::registerFactory when the module loads. Run by pk_add_plugin (cmake -P).
# The text format is described in shared/pluginkit/PresetStore.h.

file(GLOB_RECURSE files RELATIVE "${PRESET_DIR}" "${PRESET_DIR}/*.txt")
list(SORT files)

set(body "")
set(count 0)
foreach(rel IN LISTS files)
    file(READ "${PRESET_DIR}/${rel}" text)
    string(FIND "${text}" ")pkpreset\"" clash)
    if(NOT clash EQUAL -1)
        message(FATAL_ERROR "${rel}: contains the raw string delimiter )pkpreset\"")
    endif()
    string(APPEND body "    {\"${rel}\", R\"pkpreset(${text})pkpreset\"},\n")
    math(EXPR count "${count} + 1")
endforeach()

if(count EQUAL 0)
    set(content "// generated by cmake/EmbedPresets.cmake: no factory presets\n")
else()
    set(content "// generated by cmake/EmbedPresets.cmake from ${PRESET_DIR}: do not edit\n#include \"pluginkit/vst/Presets.h\"\n\nnamespace {\nconst pk::presets::FactoryFile kFactoryPresets[] = {\n${body}};\nconst bool kFactoryPresetsRegistered = pk::presets::registerFactory (kFactoryPresets, ${count});\n} // namespace\n")
endif()

# rewrite only when it changed (no needless rebuilds)
set(old "")
if(EXISTS "${OUT}")
    file(READ "${OUT}" old)
endif()
if(NOT old STREQUAL content)
    file(WRITE "${OUT}" "${content}")
endif()
